trigger:
  branches:
    include:
      - main
  paths:
    include:
      - Identity/

pr:
  autoCancel: true
  branches:
    include:
      - develop
  paths:
    include:
      - Identity/

stages:
  - stage: CI
    displayName: "Build"
    dependsOn: [ ]
    jobs:
      - template: ./azure-pipelines-ci.yaml
      - template: ./generate-config.yaml

  - stage: Migrate
    displayName: "Migrate"
    dependsOn: [ 'CI' ]
    jobs:
      - template: ./migrate-database.yaml

#  - stage: CD
#    displayName: "Deploy"
#    dependsOn: [ 'Migrate' ]
#    jobs:
#      - template: ./azure-pipelines-cd.yaml