parameters:
    artifact: 'identity'
    condition: succeeded()
    dependsOn: []
    name: ''
    workingDirectory: []

jobs:
  - job: ${{ parameters.name }}
    condition: ${{ parameters.condition }}
    dependsOn: ${{ parameters.dependsOn }}
    displayName: 'Build Identity'
    pool :
      vmImage: "ubuntu-latest"
    timeoutInMinutes: 30

    steps:
        - task: USeDotNet@2
          displayName: 'Use .NET 6 SDK'
          inputs:
            packageType: sdk
            version: 6.x

        - template: azure-pipelines-ci-build-artifact.yaml
          parameters:
            workingDirectory: '${{ parameters.workingDirectory }}'

        - powershell: |
            dotnet publish ./${{ parameters.workingDirectory }}/src/Identity.Startup/ -c Release -r linux-x64 -o $(Build.ArtifactStagingDirectory)/${{ parameters.artifact }}

        - task: CopyFiles@2
          displayName: "[Docker] Publish Dockerfile"
          inputs:
            SourceFolder: ${{ parameters.workingDirectory }}
            Contents: Dockerfile
            targetFolder: $(Build.ArtifactStagingDirectory)/${{ parameters.artifact }}

        - task: Docker@1
          displayName: "[Docker] Build image"
          inputs:
            azureSubscriptionEndpoint: travel-blog-service-connection
            azureContainerRegistry: travelblogacr
            dockerFile: '$(Build.ArtifactStagingDirectory)/${{parameters.artifact}}/Dockerfile'
            imageName: '${{parameters.artifact}}:$(Build.BuildNumber)'
            includeLatestTag: true

#        - task: Docker@1
#          displayName: "[Docker] Push image"
#          inputs:
#              azureSubscriptionEndpoint: travel-blog-service-connection
#              azureContainerRegistry: travelblogacr
#              command: 'Push an image'
#              imageName: '${{parameters.artifact}}:$(Build.BuildNumber)'
