parameters:
  condition: succeeded()
  dependsOn: [ ]

jobs:
  - job: configuration
    displayName: 'Publish configuration management for nst'
    dependsOn: ${{ parameters.dependsOn }}
    condition: ${{ parameters.condition }}
    pool:
      vmImage: "ubuntu-latest"
    
    steps:
      - task: AzureKeyVault@2
        displayName: '[configure] Read data from config kv'
        inputs:
          ConnectedServiceName: travel-blog-service-connection
          keyVaultName: travel-blog-nst-kv
          secretsFilter: >
            DatabaseConnection-Identity-ConnectionString,
            Identity-Jwt-SigningKey

      - task: PowerShell@2
        displayName: '[configure] Generate secrets variable'
        name: printSecrets
        inputs:
          pwsh: true
          targetType: inline
          script: |
            $yaml = '
            secrets:
                Database__ConnectionString: "$(DatabaseConnection-Identity-ConnectionString)"
                JwtOptions__SigningKey: "$(Identity-Certificate-SigningKey)"
            '
            $yaml_encoded = [System.Convert]::ToBase64String([System.Text.Encoding]::UTF8.GetBytes("${yaml}"))
            Write-Host "##vso[task.setvariable variable=secrets;isOutput=true]${yaml_encoded}"
      