apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity
  labels:
    app: identity
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: "identity"
  replicas: 5
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "identity"
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "travelblogacr.azurecr.io/identity:{{ .Values.buildTag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /health
              port: http
            timeoutSeconds: 30
          volumeMounts:
            - name: service-secrets
              mountPath: /config/kubernetes-secrets
              readOnly: true
      volumes:
        - name: service-secrets
          secret:
            secretName: identity-secrets

