apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: identity-hpa
  labels:
    app: identity
spec:
  scaleTargetRef:
    kind: Deployment
    name: identity
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50