apiVersion: v1
kind: Service
metadata:
  name: identity-service
  labels:
    app: identity
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      name: dotnet
  selector:
    app.kubernetes.io/name: identity
    app: identity
