apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: blog-manager-hpa
  labels:
    app: blog-manager
spec:
  scaleTargetRef:
    kind: Deployment
    name: blog-manager
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50