apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: blog-manager
  labels:
    app: blog-manager
spec:
  rules:
    - host: travel-blog-aks.northeurope.cloudapp.azure.com
      http:
        paths:
          - path : /blog_manager/api/(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: blog-manager
                port:
                  number: 80
