apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: blog-manager
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/enable-cors: "false"
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /api/$1
    nginx.ingress.kubernetes.io/service-upstream: "true"
    nginx.ingress.kubernetes.io/upstream-vhost: blog-manager
spec:
  rules:
    - host: ""
      http:
        paths:
          - path : /blog_manager/api/(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: blog-manager
                port:
                  number: 80
